export { default as Discover } from './Discover'
export { default as AroundYou } from './AroundYou'
export { default as TopArtists } from './TopArtists'
export { default as TopCharts } from './TopCharts'
export { default as Songs } from './Songs'
export { default as Artists } from './Artists'